### PR TITLE
Change webpack.config external reference of 'Flickity' to 'flickity' to fix casing in Linux

### PR DESCRIPTION
**Pull request by wadehammes**
Here this is running and working within my local instance (linux Docker container):
jul-12-2017 14-31-15

Resolves issue with #87

### CODE REVIEW

**Comment by wadehammes** [comment]
@benjamincharity mind taking a peek? It seemed to be way too simple a change, but works without error.

May need to add to the documentation, but we are using a coffee file and in order for this to work, we needed to require `flickity` and `angular-flickity` in our main app dependency file:

```
flickity = require('flickity')
bcFlickity = require('angular-flickity')
```

Without this, the app fails to instantiate. We are using Browserify.

**Comment by benjamincharity** [comment]
Sorry for the delay (again). I had an unexpected death in the family and am just now digging myself out from a mountain of notifications.

I will do my best to verify this fix in the next 48hrs. Thanks again for you patience and contributions!

**Comment by wadehammes** [comment]
@benjamincharity sorry to hear that, no worries. We have a forked copy we are using in production currently, and working really well!

**Comment by dtesta** [comment]
Been running with the same change since the end of June, also with no problems. I ran into some issues getting the unit tests back to passing and haven't had a chance to get back to them yet. Any luck on your end @wadehammes?

**Comment by benjamincharity** [comment]
I'm at a loss here...

With your change, my demo project (webpack) seems to run perfectly. However my tests fail with this error:
screen shot 2017-08-30 at 5 06 18 pm

And trying to use it in a CodePen throws this error:
screen shot 2017-08-30 at 5 08 35 pm

I'd love to release this if it solves an issue, but I can't until the tests are passing. I'll try to spend some more time on it, but as you can tell, these days my time is tight.

**Pull request closed without merging**
